### ISSUE TITLE
 invalid option '%' to 'format'

### ISSUE THREAD

**Issue by cxwx** [slugbyte/whip.nvim#1]
﻿   Error  19:29:18 notify.error lazy.nvim Failed to run `config` for whip.nvim

~/.local/share/nvim/lazy/whip.nvim/lua/whip/init.lua:28: invalid option '%' to 'format'

# stacktrace:
  - /whip.nvim/lua/whip/init.lua:28 _in_ **log_error**
  - /whip.nvim/lua/whip/init.lua:120 _in_ **dir_set**
  - /whip.nvim/lua/whip/init.lua:236 _in_ **setup**

**Comment by slugbyte** [comment]
Thanks for the bug report! Sorry for the delay in responding 

I pushed a patch to this issue :)
https://github.com/slugbyte/whip.nvim/commit/aaa97ae01c40e00c128f76a1fe2af9c7f41a920a
